version: "3.9"
networks:
  k6:
  grafana:
services:
  loadtest:
    build: .
    networks:
      - k6
    volumes:
      - ./scripts:/tests/scripts
    command: run /tests/scripts/basic.js
  chamber:
    image: ghcr.io/wilhelm-murdoch/chamber:latest
    networks:
      - k6
    ports:
      - "8000:8000"
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:9.3.8
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/